### ISSUE TITLE
In product page, the floating icon is coming behind the recently viewed section.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Tenzing-Speed-Work#5]
**Actual result:**
**The url:**  https://propervintagecanada.com/collections/all/products/vintage-floral-jones-new-york-sport-corduroy-pants-womens-size-16
In product page, the floating icon is coming behind the recently viewed section.
![image](https://user-images.githubusercontent.com/102131636/171110983-d4e786af-fd3b-48ca-ac62-c0d79e2dd35e.png)

**Expected result:**
The floating have to be visible properly in product.
**The url:**  https://propervintagecanada.com/products/vintage-protege-abstract-knit-sweater-size-large?pr_prod_strat=collection_fallback&pr_rec_id=96c2bfd91&pr_rec_pid=6873349423163&pr_ref_pid=6873368428603&pr_seq=uniform
![image](https://user-images.githubusercontent.com/102131636/171111234-25e53101-fd27-447c-9514-b18384143b5d.png)

**Comment by Ataurrahman-khan** [comment]
All Preview Pages recently viewed prodcuts  some time not visible

**Comment by sudhanshu0603** [comment]
ok, fine @Ataurrahman-khan
